# line-length = 88

# exclude = [
#     ".git",
#     ".venv",
#     "__pycache__",
#     "*.pyc",
#     ".pyenv",
#     "**/lib/python*/",
# ]

# [lint]
# select = ["ALL"]
# ignore = ["E501", "E402"]
# fixable = ["ALL"]

# [format]
# indent-style = "space"
# quote-style = "double"
# line-ending = "lf"
